deploy smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -353,10 +353,9 @@ jobs:
           command: |
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
+            if ((curl "${API_URL}/api/status" | grep "ok"))
             then
                 echo "Backend smoke test is OK"
-                return 0
             else
                 echo "Backend smoke test failed"
                 exit 1
@@ -369,20 +368,20 @@ jobs:
               if curl -s ${URL} | grep "Welcome"
               then
                   # Change this to 0 after the job fails
-                return 1
+                exit 1
               else
-                return 1
+                exit 1
               fi
-      - run: 
-          name: clean up s3 bucket
-          command: |
-            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive && aws s3 ls
-          when: on_fail
-      - destroy-environment:
-          to: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
-      - destroy-environment:
-          to: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations 
+      # - run: 
+      #     name: clean up s3 bucket
+      #     command: |
+      #       aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive && aws s3 ls
+      #     when: on_fail
+      # - destroy-environment:
+      #     to: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     to: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations 
 
   cloudfront-update:
     docker:
@@ -448,9 +447,6 @@ jobs:
             fi
             
 
-
- 
-  
 workflows:
   default:
     jobs:
